dist: trusty

language: php

php:
  - 7.1

services:
  - mysql

before_script:
  - bash .travis.install-mysql-5.7.sh
  - mysql -e 'CREATE DATABASE homestead_test CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;'
  - chmod -R 777 storage/
  - chmod -R 777 bootstrap/cache/
  - cp .env.travis.example .env
  - composer install --no-interaction
  - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - npm install --global yarn
  - yarn
  - npm run production
  - php artisan key:generate
  - php artisan migrate --database=mysql_test
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - ./vendor/laravel/dusk/bin/chromedriver-linux &
  - sleep 5 
  - php artisan serve &

script:
  - vendor/bin/phpunit
  - vendor/bin/phpunit --configuration phpunit.dusk.xml

cache:
  directories:
    - $HOME/.yarn-cache
    - node_modules
    - vendor

env:
  - TRAVIS_NODE_VERSION="8"